Add die(), option parsing, ability to supply config

diff --git a/sshtunnel b/sshtunnel
--- a/sshtunnel
+++ b/sshtunnel
@@ -48,3 +48,30 @@ conf_key() {
     done
     return 1
 }
+
+# Prints an error message and exits
+# $1: message
+# $2: exit code (optional)
+die() {
+    echo "$1" >&2
+    exit "${2:-0}"
+}
+
+while :; do
+    case "$1" in
+        -c | --config)
+            config="$2"
+            shift 2
+            ;;
+        --) # End of all options
+            shift
+            break
+            ;;
+        -*)
+            die "Unknown option: $1"
+            ;;
+        *) # All parameters shifted
+            break
+            ;;
+    esac
+done
